Fix efs_handle_delayed_submission_sameday
Theres currently an issue with the terrform that has been configured. The error is noted below for info.

Error: Missing resource instance key
  on main.tf line 153, in resource "aws_cloudwatch_event_target" "event_target_api_caller_efs_handle_delayed_submission_sameday":
 153:   rule      = aws_cloudwatch_event_rule.call_api_caller_lambda_efs_handle_delayed_submission_sameday.name
Because
aws_cloudwatch_event_rule.call_api_caller_lambda_efs_handle_delayed_submission_sameday
has "count" set, its attributes must be accessed on specific instances.